alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - 192.168.0.214:9093
rule_files:
  - /etc/prometheus/rules/*.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'zk-cluster'
    static_configs:
      - targets: ['192.168.0.211:7000','192.168.0.212:7000','192.168.0.213:7000']
  - job_name: 'mysql-cluster'
    static_configs:
      - targets: ['192.168.0.211:9104']